CREATE TABLE MDM41_TXN.ELEC_ADDR_RQST (	ELEC_ADDR_RQST_ID	INTEGER		 NOT NULL,
	PRSNA_ID	INTEGER		,
	LOB_NUM	INTEGER		,
	ELEC_ADDR_SBTYPE_CD	varchar(50)		,
	DMN_ROOT_CD	varchar(50)		,
	ELEC_ADDR_TXT	varchar(1000)		 NOT NULL,
	ELEC_ADDR_DMN_NAME	varchar(100)		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT M_ELEC_ADDR1_PK PRIMARY KEY(ELEC_ADDR_RQST_ID) 
)  ;

ALTER TABLE MDM41_TXN.ELEC_ADDR_RQST ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.ELEC_ADDR_RQST ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_TXN.ELEC_ADDR_RSULT (	ELEC_ADDR_RQST_ID	INTEGER		 NOT NULL,
	PRSNA_ID	INTEGER		,
	LOB_NUM	INTEGER		,
	ADDR_RSULT_CD	varchar(50)		,
	DMN_ROOT_CD	varchar(50)		,
	ELEC_ADDR_SBTYPE_CD	varchar(50)		,
	ELEC_ADDR_TXT	varchar(1000)		 NOT NULL,
	ELEC_ADDR_DMN_NAME	varchar(100)		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT M_ELEC_ADDR2_PK PRIMARY KEY(ELEC_ADDR_RQST_ID) 
)  ;

ALTER TABLE MDM41_TXN.ELEC_ADDR_RSULT ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.ELEC_ADDR_RSULT ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_TXN.PRSNA (	PRSNA_ID	INTEGER		 NOT NULL,
	PRSNA_SRC_ID	INTEGER		,
	FRST_NAME	varchar(100)		 NOT NULL,
	MDL_NAME	varchar(100)		 NOT NULL,
	LAST_NAME	varchar(100)		 NOT NULL,
	ORG_NAME	varchar(100)		,
	FULL_NAME	varchar(100)		,
	NICK_NAME	varchar(100)		,
	GNDR_TYPE_CD	varchar(50)		,
	USR_ID	varchar(50)		,
	USR_ACCT_STRT_DT	DATE		,
	USR_ACCT_ROLE_CD	varchar(50)		,
	STDZD_FRST_NAME	varchar(100)		,
	STDZD_LAST_NAME	varchar(100)		,
	STDZD_MDL_NAME	varchar(100)		,
	PRSNA_ROLE_CD	varchar(50)		,
	UNVRSL_AUTHZTN_LANG_CD	varchar(50)		,
	PRSNA_BUS_DT	DATE		,
	UNVRSL_AUTHZTN_STRT_DT	DATE		,
	SOC_GRP_NAME	varchar(100)		,
	MKTG_PRG_ID	INTEGER		,
	SRC_INTAKE_ID	varchar(18)		 NOT NULL,
	LOB_NUM	INTEGER		 NOT NULL,
	PRTNR_NAME	varchar(20)		,
	NAME_PRFX	varchar(20)		,
	NAME_SFX	varchar(20)		,
	PREFD_LANG	varchar(50)		,
	TERMS_ACPTNC_DT	TIMESTAMP(0)		,
	CMUNCTN_TM_ZN	varchar(20)		,
	LEAD_NUM	varchar(20)		,
	ETHCTY_TYPE_CD	varchar(50)		,
	USR_RGSTRN_DT	TIMESTAMP(0)		,
	UNVRSL_OPT_IND	char(1)		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT M_PRSNA_PK PRIMARY KEY(PRSNA_ID,LOB_NUM) 
)  ;

ALTER TABLE MDM41_TXN.PRSNA ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.PRSNA ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_TXN.PRSNA_ACCT (	ACCT_NUM	varchar(50)		 NOT NULL,
	PRSNA_ID	INTEGER		 NOT NULL,
	FRST_NAME	varchar(100)		 NOT NULL,
	MDL_NAME	varchar(100)		 NOT NULL,
	LAST_NAME	varchar(100)		 NOT NULL,
	LOB_NUM	INTEGER		 NOT NULL,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT M_PRSNA_ACCT_PK PRIMARY KEY(ACCT_NUM,PRSNA_ID,LOB_NUM) 
)  PRIMARY INDEX MST_XIE1PRSNA_ACCOUNT (PRSNA_ID) 
 ;

ALTER TABLE MDM41_TXN.PRSNA_ACCT ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.PRSNA_ACCT ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_TXN.PRSNA_ADDR (	PRSNA_ID	INTEGER		 NOT NULL,
	ADDR_SUBTYPE_CD	varchar(50)		,
	ADDR_RQST_ID	INTEGER		 NOT NULL,
	ADDR_STDZD_TXT	varchar(1000)		,
	CHNL_ID	INTEGER		,
	ADDR_TYPE_CD	varchar(50)		,
	CNTCT_OPT_IND	char(1)		,
	UAL_CD	varchar(50)		,
	ADDR_IGNORE_FLG	char(1)		,
	LOB_NUM	INTEGER		 NOT NULL,
	PERSONNA_ADDR_STRT_DT	TIMESTAMP(0)		,
	PERSONNA_ADDR_END_DT	TIMESTAMP(0)		,
	ADDR_STS_CD	varchar(20)		,
	SMS_ALLWD_CD	char(1)		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT M_PRSNA_ADDR_PK PRIMARY KEY(PRSNA_ID,ADDR_RQST_ID,LOB_NUM) 
)  PRIMARY INDEX MST_XIE1PRSNA_ADDRESS (PRSNA_ID) 
 ;

ALTER TABLE MDM41_TXN.PRSNA_ADDR ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.PRSNA_ADDR ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_TXN.PRSNA_ADDR_XREF (	ADDR_RQST_ID	INTEGER		 NOT NULL,
	PRSNA_ID	INTEGER		 NOT NULL,
	XREF_KEY1	varchar(1000)		,
	LOB_NUM	INTEGER		 NOT NULL,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT M_PRSNA_ADD3_PK PRIMARY KEY(ADDR_RQST_ID,PRSNA_ID,LOB_NUM) 
)  PRIMARY INDEX MST_XIE1PRSNA_ADDRESS_XREF (PRSNA_ID) 
 ;

ALTER TABLE MDM41_TXN.PRSNA_ADDR_XREF ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.PRSNA_ADDR_XREF ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_TXN.PRSNA_CNTCT_PREF (	PRSNA_ID	INTEGER		 NOT NULL,
	ADDR_RQST_ID	INTEGER		 NOT NULL,
	LOB_NUM	INTEGER		 NOT NULL,
	CNTCT_PREFRC_TM_PRD_CD	varchar(50)		 NOT NULL,
	CNTRCT_PREFRC_CYCL_CD	varchar(50)		,
	CNTCT_PREFRC_STRT_TM	TIMESTAMP(0)		,
	CNTCT_PREFRC_END_TM	TIMESTAMP(0)		,
	CNTCT_PREFRC_FRQCY_NUM	varchar(50)		,
	CNTCT_PREFRC_CNT	INTEGER		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT M_PRSNA_CNT4_PK PRIMARY KEY(PRSNA_ID,ADDR_RQST_ID,LOB_NUM,CNTCT_PREFRC_TM_PRD_CD) 
)  PRIMARY INDEX MST_XIE1PRSNA_CONTACT_PREFERENCE_TIME_PERIOD (PRSNA_ID) 
 ;


ALTER TABLE MDM41_TXN.PRSNA_CNTCT_PREF ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.PRSNA_CNTCT_PREF ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_TXN.PRSNA_PROD (	PRSNA_ID	INTEGER		 NOT NULL,
	MKTG_PRG_ID	INTEGER		,
	CHNL_ID	INTEGER		 NOT NULL,
	BRND_CD	varchar(50)		,
	PROD_ID	INTEGER		 NOT NULL,
	LOB_NUM	INTEGER		 NOT NULL,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT M_PRSNA_PROD_PK PRIMARY KEY(PRSNA_ID,PROD_ID,LOB_NUM) 
)  PRIMARY INDEX MST_XIE1PRSNA_PRODUCT (PRSNA_ID) 
 ;

ALTER TABLE MDM41_TXN.PRSNA_PROD ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.PRSNA_PROD ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_TXN.PRSNA_RLTNSHP (	PARNT_PRSNA_ID	INTEGER		 NOT NULL,
	CHLD_PRSNA_ID	INTEGER		 NOT NULL,
	PRSNA_RLTNSHP_TYPE_CD	varchar(50)		 NOT NULL,
	PRSNA_RLTNSHP_ROLE_CD	varchar(50)		 NOT NULL,
	LOB_NUM	INTEGER		 NOT NULL,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT M_PRSNA_RLTNSHP_PK PRIMARY KEY(PARNT_PRSNA_ID,CHLD_PRSNA_ID,LOB_NUM) 
)  PRIMARY INDEX MST_XIE1PRSNA_RELATIONSHIP (CHLD_PRSNA_ID) 
 ;

ALTER TABLE MDM41_TXN.PRSNA_RLTNSHP ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.PRSNA_RLTNSHP ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_TXN.PRSNA_SRC_CHNL (	PRSNA_SRC_TYPE_CD	varchar(50)		 NOT NULL,
	CHNL_ID	INTEGER		 NOT NULL,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT M_PRSNA_SRC5_PK PRIMARY KEY(PRSNA_SRC_TYPE_CD,CHNL_ID) 
)  ;

ALTER TABLE MDM41_TXN.PRSNA_SRC_CHNL ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.PRSNA_SRC_CHNL ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_TXN.PRSNA_SRC_TYPE (	PRSNA_SRC_TYPE_CD	varchar(50)		 NOT NULL,
	PRSNA_SRC_TYPE_DESC	varchar(250)		,
	PRSNA_SRC_TYPE_NAME	varchar(100)		,
	SRC_PRVDR_CD	varchar(50)		,
	SRC_FLDR_TXT	varchar(1000)		,
	SFTP_FLG	char(3)		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT M_PRSNA_SRC6_PK PRIMARY KEY(PRSNA_SRC_TYPE_CD) 
)  ;

ALTER TABLE MDM41_TXN.PRSNA_SRC_TYPE ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.PRSNA_SRC_TYPE ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_TXN.PRSNA_TRAIT (	PRSNA_ID	INTEGER		 NOT NULL,
	TRAIT_CD	varchar(50)		 NOT NULL,
	TRAIT_VAL	varchar(100)		 NOT NULL,
	MKTG_PRG_ID	INTEGER		,
	PRSNA_TRAIT_STRT_DT	DATE		 NOT NULL,
	PRSNA_TRAIT_END_DT	DATE		,
	CHNL_ID	INTEGER		 NOT NULL,
	TRAIT_SEQ_ID	INTEGER		 NOT NULL,
	LOB_NUM	INTEGER		 NOT NULL,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT M_PRSNA_TRAIT_PK PRIMARY KEY(PRSNA_ID,TRAIT_CD,TRAIT_SEQ_ID,LOB_NUM) 
)  PRIMARY INDEX MST_TRAIT_CD_PI_5801467 (TRAIT_CD) 
 ;

CREATE INDEX MST_XIE1PRSNA_TRAIT (PRSNA_ID) ON MDM41_TXN.PRSNA_TRAIT ;

ALTER TABLE MDM41_TXN.PRSNA_TRAIT ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.PRSNA_TRAIT ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_TXN.PRSNA_XREF (	PRSNA_ID	INTEGER		 NOT NULL,
	XREF_KEY1	varchar(1000)		,
	XREF_KEY2	varchar(1000)		,
	LOB_NUM	INTEGER		 NOT NULL,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_PRSNA_XREF_PK PRIMARY KEY(PRSNA_ID,LOB_NUM) 
)  PRIMARY INDEX MST_PRSNA_ID_PI_1323827 (PRSNA_ID) 
 ;

ALTER TABLE MDM41_TXN.PRSNA_XREF ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.PRSNA_XREF ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_TXN.STREET_ADDR_RQST (	PRSNA_ID	INTEGER		,
	STREET_ADDR_RQST_ID	INTEGER		 NOT NULL,
	ADDR_LINE_1_TXT	varchar(1000)		,
	ADDR_LINE_2_TXT	varchar(1000)		,
	ADDR_LINE_3_TXT	varchar(1000)		,
	ADDR_LINE_4_TXT	varchar(1000)		,
	ST_OR_PROV_CD	varchar(50)		,
	CITY_NAME	varchar(100)		,
	POSTL_CD	varchar(50)		,
	LAT_MEAS	DECIMAL(18,4)		,
	LNGTD_MEAS	DECIMAL(18,4)		,
	CTRY_ID	INTEGER		,
	GEO_ACRCY_CD	varchar(50)		,
	ORG_CD	varchar(50)		,
	BLDG_ID	INTEGER		,
	SUB_BLDG_ID	INTEGER		,
	PREMS_CD	varchar(50)		,
	THOROUGHFARE_CD	varchar(50)		,
	LOB_NUM	INTEGER		,
	DSTRCT_NAME	varchar(50)		,
	CNTY_NAME	varchar(50)		,
	ZIP_EXTN	varchar(20)		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT M_STREET_AD7_PK PRIMARY KEY(STREET_ADDR_RQST_ID) 
)  ;

ALTER TABLE MDM41_TXN.STREET_ADDR_RQST ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.STREET_ADDR_RQST ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_TXN.STREET_ADDR_RSULT (	PRSNA_ID	INTEGER		,
	STREET_ADDR_RQST_ID	INTEGER		 NOT NULL,
	ADDR_LINE_1_TXT	varchar(1000)		,
	ADDR_LINE_2_TXT	varchar(1000)		,
	ADDR_LINE_3_TXT	varchar(1000)		,
	ADDR_LINE_4_TXT	varchar(1000)		,
	ST_OR_PROV_CD	varchar(50)		,
	CITY_NAME	varchar(100)		,
	POSTL_CD	varchar(50)		,
	LAT_MEAS	DECIMAL(18,4)		,
	LNGTD_MEAS	DECIMAL(18,4)		,
	CTRY_ID	INTEGER		,
	GEO_ACRCY_CD	varchar(50)		,
	ORG_CD	varchar(50)		,
	BLDG_ID	INTEGER		,
	SUB_BLDG_ID	INTEGER		,
	PREMS_CD	varchar(50)		,
	THOROUGHFARE_CD	varchar(50)		,
	ADDR_RSULT_CD	varchar(50)		,
	LOB_NUM	INTEGER		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT M_STREET_AD8_PK PRIMARY KEY(STREET_ADDR_RQST_ID) 
)  ;

ALTER TABLE MDM41_TXN.STREET_ADDR_RSULT ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.STREET_ADDR_RSULT ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_TXN.TEL_NUM_RQST (	TEL_NUM_RQST_ID	INTEGER		 NOT NULL,
	TEL_CTRY_CD_NUM	varchar(50)		,
	TEL_AREA_CD_NUM	varchar(50)		,
	TEL_EXCH_NUM	varchar(50)		,
	TEL_LINE_NUM	varchar(50)		,
	TEL_EXTN_NUM	varchar(50)		,
	TEL_E164_NUM	varchar(50)		,
	TEL_SRC_NUM	varchar(50)		,
	TEL_SUB_TYPE_CD	varchar(50)		,
	PRSNA_ID	INTEGER		,
	LOB_NUM	INTEGER		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT M_TEL_NUM_RQST_PK PRIMARY KEY(TEL_NUM_RQST_ID) 
)  ;

ALTER TABLE MDM41_TXN.TEL_NUM_RQST ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.TEL_NUM_RQST ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_TXN.TEL_NUM_RSULT (	TEL_NUM_RQST_ID	INTEGER		 NOT NULL,
	PRSNA_ID	INTEGER		,
	TEL_CTRY_CD_NUM	varchar(50)		,
	TEL_AREA_CD_NUM	varchar(50)		,
	TEL_EXCH_NUM	varchar(50)		,
	TEL_LINE_NUM	varchar(50)		,
	TEL_EXTN_NUM	varchar(50)		,
	TEL_E164_NUM	varchar(50)		,
	TEL_SRC_NUM	varchar(50)		,
	TEL_SUB_TYPE_CD	varchar(50)		,
	ADDR_RSULT_CD	varchar(50)		,
	TEL_NATL_FMT_NUM	char(18)		,
	TEL_TM_ZN_CD	char(18)		,
	TEL_OFFLN_GEOCODE_LOC_CD	char(18)		,
	TEL_INTRNATL_FMT_NUM	char(18)		,
	US_OUT_OF_CTRY_FMT_NUM	char(18)		,
	CH_OUT_OF_CTRY_FMT_NUM	char(18)		,
	LOB_NUM	INTEGER		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		)  ;

ALTER TABLE MDM41_TXN.TEL_NUM_RSULT ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.TEL_NUM_RSULT ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 


----------------------------------------------------------------------------------------------------


CREATE TABLE MDM41_TXN.DEVICE_DATA (	DEVICE_ID	INTEGER		 NOT NULL,
	DEVICE_TYPE_CD	varchar(50)		,
	IMEI	varchar(20)		,
	MOB_EQUIP_ID	varchar(20)		,
	VISOR_NUM	varchar(20)		,
	TELEMATICS_CNTRL_UNIT_NUM	varchar(256)		,
	ICCID	varchar(20)		,
	MSISDN	varchar(20)		,
	SFTWR_VERS	varchar(20)		,
	SFTWR_UPD_DT	DATE		,
	DEACT_DT	DATE		,
	DEVICE_PRVSN_DT	DATE		,
	DEVICE_DSTRBR_NAME	varchar(50)		,
	MFGR_SER_NUM	varchar(256)		,
	DEVICE_MODL_NUM	varchar(20)		,
	DEVICE_ASMBLY_DT	DATE		,
	MOB_DIR_NUM	varchar(20)		,
	MOB_IDNTFTN_NUM	varchar(20)		,
	EQUIP_SER_NUM	varchar(20)		,
	MSI	varchar(20)		,
	MFGNG_DT	DATE		,
	MFGR_NAME	varchar(50)		,
	SRC_INTAKE_ID	varchar(18)		,
	DEVICE_STS	varchar(20)		,
	ORIGNL_ACTVTN_DT	DATE		,
	LOB_NUM	INTEGER		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_DEVICE_3_PK PRIMARY KEY(DEVICE_ID) 
)  ;


ALTER TABLE MDM41_TXN.DEVICE_DATA ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.DEVICE_DATA ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 


CREATE TABLE MDM41_TXN.DEVICE_FEAT_DATA (	DEVICE_ID	INTEGER		 NOT NULL,
	FEAT_CD	varchar(20)		 NOT NULL,
	FEAT_SETUP_STRT_DT	TIMESTAMP(0)		,
	FEAT_SETUP_END_DT	TIMESTAMP(0)		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_DEVICE_4_PK PRIMARY KEY(DEVICE_ID,FEAT_CD) 
)  PRIMARY INDEX MST_XIE1DEVICE_FEATURE_DATA (DEVICE_ID) 
 ;


ALTER TABLE MDM41_TXN.DEVICE_FEAT_DATA ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.DEVICE_FEAT_DATA ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 


CREATE TABLE MDM41_TXN.DEVICE_PRSNA (	PRSNA_ID	INTEGER		 NOT NULL,
	DEVICE_ID	INTEGER		 NOT NULL,
	LOB_NUM	INTEGER		 NOT NULL,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_DEVICE_6_PK PRIMARY KEY(PRSNA_ID,DEVICE_ID,LOB_NUM) 
)  PRIMARY INDEX MST_XIE1DEVICE_PRSNA (PRSNA_ID) 
 ;

ALTER TABLE MDM41_TXN.DEVICE_PRSNA ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.DEVICE_PRSNA ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_TXN.DEVICE_XREF (	DEVICE_ID	INTEGER		 NOT NULL,
	XREF_KEY1	varchar(1000)		,
	SRC_INTAKE_ID	varchar(1000)		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_DEVICE_7_PK PRIMARY KEY(DEVICE_ID) 
)  ;

ALTER TABLE MDM41_TXN.DEVICE_XREF ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.DEVICE_XREF ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_TXN.DLR (	DLR_CD	varchar(20)		 NOT NULL,
	DLR_NAME	varchar(100)		,
	PRTNR_NAME	varchar(20)		 NOT NULL,
	DLR_RGN_NAME	varchar(50)		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_DLR_PK PRIMARY KEY(DLR_CD,PRTNR_NAME) 
)  PRIMARY INDEX MST_XIE1DEALER (DLR_CD) 
 ;

ALTER TABLE MDM41_TXN.DLR ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.DLR ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 


CREATE TABLE MDM41_TXN.SALES_PERSON (	DLR_CD	varchar(20)		 NOT NULL,
	SLS_PRSN_USR_ID	varchar(20)		,
	SLS_PRSN_NUM	varchar(20)		 NOT NULL,
	PRTNR_NAME	varchar(20)		 NOT NULL,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_SALES_P22_PK PRIMARY KEY(DLR_CD,SLS_PRSN_NUM,PRTNR_NAME) 
)  PRIMARY INDEX MST_XIE1SALES_PERSON (DLR_CD) 
 ;

ALTER TABLE MDM41_TXN.SALES_PERSON ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.SALES_PERSON ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 


CREATE TABLE MDM41_TXN.VEH_DATA (	VEH_ID	INTEGER		 NOT NULL,
	VEH_YR	varchar(20)		,
	MODL_TRIM	varchar(50)		,
	SHPG_DT	DATE		,
	ORIGNL_SLS_DT	DATE		,
	MFGNG_DT	DATE		,
	EURO_FIN	varchar(20)		,
	BODY_STYL_CD	varchar(20)		,
	DOOR_STYL_CD	varchar(20)		,
	FUEL_TYPE_CD	varchar(20)		,
	NVGTN_CD	varchar(20)		,
	TELEMATICS_CD	varchar(20)		,
	HD_UNIT_TYPE_CD	varchar(20)		,
	HD_UNIT_SER_NUM	varchar(50)		,
	HD_UNIT_MODL_NUM	varchar(20)		,
	LIC_PLATE_NUM	varchar(20)		,
	LIC_PLATE_ST	char(2)		,
	VEH_CTGY_CD	varchar(20)		,
	USED_CAR_SLS_IND	char(1)		,
	FLEET_CAR_IND	char(1)		,
	CPO_IND	char(1)		,
	IMPORT_IND	char(1)		,
	NEW_CAR_IND	char(1)		,
	CNTCT_NUM	varchar(20)		,
	PRTNR_NAME	varchar(20)		,
	VEH_VIN	varchar(20)		,
	VIN_PTN	varchar(20)		,
	SRC_INTAKE_ID	varchar(18)		,
	FACTORY_SHPG_DT	DATE		,
	VEH_SLS_MODL_CD	varchar(20)		,
	VEH_MAKE_CD	varchar(20)		,
	VEH_INTRIOR_COLOR_CD	varchar(20)		,
	VEH_EXTRR_COLOR_CD	varchar(20)		,
	ENGN_SLS_NUM	varchar(20)		,
	VEHCILE_SER_NUM	varchar(20)		,
	VEH_ORIGNL_DLR_CD	varchar(20)		,
	ORIGNL_DLR_CD	varchar(20)		,
	ORIGNL_PRTNR_NAME	varchar(20)		,
	VEH_RCALLD_IND	char(1)		,
	XMISN_SER_NUM	varchar(20)		,
	MFGNG_CTRY_CD	varchar(20)		,
	XMISN_TYPE_CD	varchar(20)		,
	DEVICE_ID	INTEGER		,
	LOB_NUM	INTEGER		,
	OEM_MFGR_ID	INTEGER		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_VEH_DAT29_PK PRIMARY KEY(VEH_ID) 
)  ;

ALTER TABLE MDM41_TXN.VEH_DATA ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.VEH_DATA ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_TXN.VEH_FEAT_DATA (	FEAT_CD	varchar(20)		 NOT NULL,
	VEH_ID	INTEGER		 NOT NULL,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_VEH_FEA30_PK PRIMARY KEY(FEAT_CD,VEH_ID) 
)  PRIMARY INDEX MST_XIE1VEHICLE_FEATURE_DATA (VEH_ID) 
 ;

ALTER TABLE MDM41_TXN.VEH_FEAT_DATA ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.VEH_FEAT_DATA ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_TXN.VEH_MFG_DATA (	VEH_ID	INTEGER		 NOT NULL,
	VEH_MFG_DATA_CD	varchar(20)		 NOT NULL,
	VEH_MFG_DATA_MEAS_CD	varchar(20)		,
	VEH_MFG_DATA_VAL	DECIMAL(18,4)		,
	VEH_MFG_DATA_DESC	varchar(250)		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_VEH_MFG31_PK PRIMARY KEY(VEH_ID) 
)  ;

ALTER TABLE MDM41_TXN.VEH_MFG_DATA ADD CONSTRAINT MST_XPKVEHICLE_MANUFACTURER_DATA UNIQUE (VEH_ID, VEH_MFG_DATA_CD) ;

ALTER TABLE MDM41_TXN.VEH_MFG_DATA ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.VEH_MFG_DATA ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_TXN.VEH_PRSNA (	VEH_ID	INTEGER		 NOT NULL,
	PRSNA_ID	INTEGER		 NOT NULL,
	LOB_NUM	INTEGER		 NOT NULL,
	PRSNA_ROLE_CD	varchar(50)		,
	SELG_DLR_CD	varchar(20)		,
	SLS_PRSN_NUM	varchar(20)		,
	SELG_PRTNR_NAME	varchar(20)		,
	FRST_OWNR_IND	char(1)		,
	LAST_PREOWNED_DT	DATE		,
	SRVCG_DLR_CD	varchar(20)		,
	SRVCG_PRTNR_NAME	varchar(50)		,
	LEASG_CO_NAME	varchar(50)		,
	EU_DLVRY_IND	char(1)		,
	VEH_SLS_DT	DATE		,
	VEH_SLS_RPT_DT	DATE		,
	VEH_PRSNA_RLTNSHP_TYPE_CD	varchar(20)		,
	PO	varchar(20)		,
	CURR_MILEG	INTEGER		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_VEH_PRS32_PK PRIMARY KEY(VEH_ID,PRSNA_ID,LOB_NUM) 
)  PRIMARY INDEX MST_XIE1VEHICLE_PRSNA (PRSNA_ID) 
 ;

ALTER TABLE MDM41_TXN.VEH_PRSNA ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.VEH_PRSNA ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_TXN.VEH_XREF (	VEH_ID	INTEGER		 NOT NULL,
	XREF_KEY	varchar(20)		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_VEH_XRE33_PK PRIMARY KEY(VEH_ID) 
)  PRIMARY INDEX MST_XREF_KEY_PI_9937834 (XREF_KEY) 
 ;

ALTER TABLE MDM41_TXN.VEH_XREF ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_TXN.VEH_XREF ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 
