
CREATE TABLE MDM41_STG.DEVICE_DATA_STG (	DEVICE_ID	INTEGER		 NOT NULL,
	DEVICE_TYPE_CD	varchar(50)		,
	IMEI	varchar(20)		,
	MOB_EQUIP_ID	varchar(20)		,
	VISOR_NUM	varchar(20)		,
	TELEMATICS_CNTRL_UNIT_NUM	varchar(256)		,
	ICCID	varchar(20)		,
	MSISDN	varchar(20)		,
	SFTWR_VERS	varchar(20)		,
	SFTWR_UPD_DT	DATE		,
	DEACT_DT	DATE		,
	DEVICE_PRVSN_DT	DATE		,
	DEVICE_DSTRBR_NAME	varchar(50)		,
	MFGR_SER_NUM	varchar(256)		,
	DEVICE_MODL_NUM	varchar(20)		,
	DEVICE_ASMBLY_DT	DATE		,
	MOB_DIR_NUM	varchar(20)		,
	MOB_IDNTFTN_NUM	varchar(20)		,
	EQUIP_SER_NUM	varchar(20)		,
	MSI	varchar(20)		,
	MFGNG_DT	DATE		,
	MFGR_NAME	varchar(50)		,
	SRC_INTAKE_ID	varchar(18)		,
	DEVICE_STS	varchar(20)		,
	ORIGNL_ACTVTN_DT	DATE		,
	LOB_NUM	INTEGER		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_DEVICE_3_PK PRIMARY KEY(DEVICE_ID) 
)  ;


ALTER TABLE MDM41_STG.DEVICE_DATA_STG ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_STG.DEVICE_DATA_STG ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 


CREATE TABLE MDM41_STG.DEVICE_FEAT_DATA_STG (	DEVICE_ID	INTEGER		 NOT NULL,
	FEAT_CD	varchar(20)		 NOT NULL,
	FEAT_SETUP_STRT_DT	TIMESTAMP(0)		,
	FEAT_SETUP_END_DT	TIMESTAMP(0)		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_DEVICE_4_PK PRIMARY KEY(DEVICE_ID,FEAT_CD) 
)  PRIMARY INDEX MST_XIE1DEVICE_FEATURE_DATA (DEVICE_ID) 
 ;


ALTER TABLE MDM41_STG.DEVICE_FEAT_DATA_STG ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_STG.DEVICE_FEAT_DATA_STG ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 


CREATE TABLE MDM41_STG.DEVICE_PRSNA_STG (	PRSNA_ID	INTEGER		 NOT NULL,
	DEVICE_ID	INTEGER		 NOT NULL,
	LOB_NUM	INTEGER		 NOT NULL,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_DEVICE_6_PK PRIMARY KEY(PRSNA_ID,DEVICE_ID,LOB_NUM) 
)  PRIMARY INDEX MST_XIE1DEVICE_PRSNA (PRSNA_ID) 
 ;

ALTER TABLE MDM41_STG.DEVICE_PRSNA_STG ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_STG.DEVICE_PRSNA_STG ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_STG.DEVICE_XREF_STG (	DEVICE_ID	INTEGER		 NOT NULL,
	XREF_KEY1	varchar(1000)		,
	SRC_INTAKE_ID	varchar(1000)		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_DEVICE_7_PK PRIMARY KEY(DEVICE_ID) 
)  ;

ALTER TABLE MDM41_STG.DEVICE_XREF_STG ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_STG.DEVICE_XREF_STG ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_STG.DLR_STG (	DLR_CD	varchar(20)		 NOT NULL,
	DLR_NAME	varchar(100)		,
	PRTNR_NAME	varchar(20)		 NOT NULL,
	DLR_RGN_NAME	varchar(50)		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_DLR_STG_PK PRIMARY KEY(DLR_CD,PRTNR_NAME) 
)  PRIMARY INDEX MST_XIE1DEALER (DLR_CD) 
 ;

ALTER TABLE MDM41_STG.DLR_STG ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_STG.DLR_STG ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_STG.ELEC_ADDR_RQST_STG (	ELEC_ADDR_RQST_ID	INTEGER		 NOT NULL,
	PRSNA_ID	INTEGER		,
	DMN_ROOT_CD	varchar(50)		,
	ELEC_ADDR_SBTYPE_CD	varchar(50)		,
	ELEC_ADDR_TXT	varchar(1000)		 NOT NULL,
	ELEC_ADDR_DMN_NAME	varchar(100)		,
	LOB_NUM	INTEGER		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_ELEC_AD9_PK PRIMARY KEY(ELEC_ADDR_RQST_ID) 
)  ;

ALTER TABLE MDM41_STG.ELEC_ADDR_RQST_STG ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_STG.ELEC_ADDR_RQST_STG ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 


CREATE TABLE MDM41_STG.ELEC_ADDR_RSULT_STG (	ELEC_ADDR_RQST_ID	INTEGER		 NOT NULL,
	PRSNA_ID	INTEGER		,
	DMN_ROOT_CD	varchar(50)		,
	ELEC_ADDR_SBTYPE_CD	varchar(50)		,
	ELEC_ADDR_TXT	varchar(1000)		 NOT NULL,
	ELEC_ADDR_DMN_NAME	varchar(100)		,
	ADDR_RSULT_CD	varchar(50)		,
	LOB_NUM	INTEGER		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_ELEC_AD11_PK PRIMARY KEY(ELEC_ADDR_RQST_ID) 
)  ;

ALTER TABLE MDM41_STG.ELEC_ADDR_RSULT_STG ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_STG.ELEC_ADDR_RSULT_STG ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_STG.PRSNA_ACCT_STG (	ACCT_NUM	varchar(50)		 NOT NULL,
	PRSNA_ID	INTEGER		 NOT NULL,
	FRST_NAME	varchar(100)		 NOT NULL,
	MDL_NAME	varchar(100)		 NOT NULL,
	LAST_NAME	varchar(100)		 NOT NULL,
	LOB_NUM	INTEGER		 NOT NULL,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_PRSNA_A12_PK PRIMARY KEY(ACCT_NUM,PRSNA_ID,LOB_NUM) 
)  PRIMARY INDEX MST_XIE1PRSNA_ACCOUNT (PRSNA_ID) 
 ;

ALTER TABLE MDM41_STG.PRSNA_ACCT_STG ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_STG.PRSNA_ACCT_STG ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_STG.PRSNA_ADDR_STG (	PRSNA_ID	INTEGER		 NOT NULL,
	ADDR_RQST_ID	INTEGER		 NOT NULL,
	ADDR_TYPE_CD	varchar(50)		,
	ADDR_SUBTYPE_CD	varchar(50)		,
	LOB_NUM	INTEGER		 NOT NULL,
	CHNL_ID	INTEGER		,
	ADDR_STDZD_TXT	varchar(1000)		,
	CNTCT_OPT_IND	char(1)		,
	UAL_CD	varchar(50)		,
	ADDR_IGNORE_FLG	char(1)		,
	PERSONNA_ADDR_STRT_DT	TIMESTAMP(0)		,
	PERSONNA_ADDR_END_DT	TIMESTAMP(0)		,
	ADDR_STS_CD	varchar(20)		,
	SMS_ALLWD_CD	char(1)		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_PRSNA_A13_PK PRIMARY KEY(PRSNA_ID,ADDR_RQST_ID,LOB_NUM) 
)  PRIMARY INDEX MST_XIE1PRSNA_ADDRESS (PRSNA_ID) 
 ;

ALTER TABLE MDM41_STG.PRSNA_ADDR_STG ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_STG.PRSNA_ADDR_STG ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_STG.PRSNA_ADDR_XREF_STG (	ADDR_RQST_ID	INTEGER		 NOT NULL,
	PRSNA_ID	INTEGER		 NOT NULL,
	XREF_KEY1	varchar(1000)		,
	LOB_NUM	INTEGER		 NOT NULL,
	SRC_INTAKE_ID	varchar(18)		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_PRSNA_A15_PK PRIMARY KEY(ADDR_RQST_ID,PRSNA_ID,LOB_NUM) 
)  PRIMARY INDEX MST_XIE1PRSNA_ADDRESS_XREF (PRSNA_ID) 
 ;

ALTER TABLE MDM41_STG.PRSNA_ADDR_XREF_STG ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_STG.PRSNA_ADDR_XREF_STG ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_STG.PRSNA_RLTNSHP_STG (	PARNT_PRSNA_ID	INTEGER		 NOT NULL,
	CHLD_PRSNA_ID	INTEGER		 NOT NULL,
	PRSNA_RLTNSHP_TYPE_CD	varchar(50)		 NOT NULL,
	PRSNA_RLTNSHP_ROLE_CD	varchar(50)		 NOT NULL,
	LOB_NUM	INTEGER		 NOT NULL,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_PRSNA_R17_PK PRIMARY KEY(PARNT_PRSNA_ID,CHLD_PRSNA_ID,LOB_NUM) 
)  PRIMARY INDEX MST_XIE1PRSNA_RELATIONSHIP (CHLD_PRSNA_ID) 
 ;

ALTER TABLE MDM41_STG.PRSNA_RLTNSHP_STG ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_STG.PRSNA_RLTNSHP_STG ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_STG.PRSNA_STG (	PRSNA_ID	INTEGER		 NOT NULL,
	PRSNA_SRC_ID	INTEGER		,
	FRST_NAME	varchar(100)		 NOT NULL,
	MDL_NAME	varchar(100)		 NOT NULL,
	LAST_NAME	varchar(100)		 NOT NULL,
	ORG_NAME	varchar(100)		,
	FULL_NAME	varchar(100)		,
	GNDR_TYPE_CD	varchar(50)		,
	USR_ID	varchar(50)		,
	USR_ACCT_STRT_DT	DATE		,
	USR_ACCT_ROLE_CD	varchar(50)		,
	STDZD_FRST_NAME	varchar(100)		,
	STDZD_LAST_NAME	varchar(100)		,
	STDZD_MDL_NAME	varchar(100)		,
	PRSNA_ROLE_CD	varchar(50)		,
	NICK_NAME	varchar(100)		,
	UNVRSL_AUTHZTN_LANG_CD	varchar(50)		,
	PRSNA_BUS_DT	DATE		,
	UNVRSL_AUTHZTN_STRT_DT	DATE		,
	SOC_GRP_NAME	varchar(100)		,
	MKTG_PRG_ID	INTEGER		,
	LOB_NUM	INTEGER		 NOT NULL,
	PRTNR_NAME	varchar(20)		,
	NAME_PRFX	varchar(20)		,
	NAME_SFX	varchar(20)		,
	PREFD_LANG	varchar(50)		,
	TERMS_ACPTNC_DT	TIMESTAMP(0)		,
	CMUNCTN_TM_ZN	varchar(20)		,
	LEAD_NUM	varchar(20)		,
	ETHCTY_TYPE_CD	varchar(50)		,
	USR_RGSTRN_DT	TIMESTAMP(0)		,
	UNVRSL_OPT_IND	char(1)		,
	SRC_INTAKE_ID	varchar(18)		 NOT NULL,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_PRSNA_STG_PK PRIMARY KEY(PRSNA_ID,LOB_NUM) 
)  ;

ALTER TABLE MDM41_STG.PRSNA_STG ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_STG.PRSNA_STG ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_STG.PRSNA_XREF_STG (	PRSNA_ID	INTEGER		 NOT NULL,
	XREF_KEY1	varchar(1000)		,
	LOB_NUM	INTEGER		 NOT NULL,
	SRC_INTAKE_ID	varchar(18)		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_PRSNA_X20_PK PRIMARY KEY(PRSNA_ID,LOB_NUM) 
)  PRIMARY INDEX MST_PRSNA_ID_PI_1323827 (PRSNA_ID) 
 ;

ALTER TABLE MDM41_STG.PRSNA_XREF_STG ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_STG.PRSNA_XREF_STG ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_STG.SALES_PERSON_STG (	DLR_CD	varchar(20)		 NOT NULL,
	SLS_PRSN_USR_ID	varchar(20)		,
	SLS_PRSN_NUM	varchar(20)		 NOT NULL,
	PRTNR_NAME	varchar(20)		 NOT NULL,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_SALES_P22_PK PRIMARY KEY(DLR_CD,SLS_PRSN_NUM,PRTNR_NAME) 
)  PRIMARY INDEX MST_XIE1SALES_PERSON (DLR_CD) 
 ;

ALTER TABLE MDM41_STG.SALES_PERSON_STG ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_STG.SALES_PERSON_STG ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_STG.STREET_ADDR_RQST_STG (	STREET_ADDR_RQST_ID	INTEGER		 NOT NULL,
	PRSNA_ID	INTEGER		,
	ADDR_LINE_1_TXT	varchar(1000)		,
	ADDR_LINE_2_TXT	varchar(1000)		,
	ADDR_LINE_3_TXT	varchar(1000)		,
	ADDR_LINE_4_TXT	varchar(1000)		,
	ST_OR_PROV_CD	varchar(50)		,
	CITY_NAME	varchar(100)		,
	POSTL_CD	varchar(50)		,
	LAT_MEAS	DECIMAL(18,4)		,
	LNGTD_MEAS	DECIMAL(18,4)		,
	CTRY_ID	INTEGER		,
	GEO_ACRCY_CD	varchar(50)		,
	ORG_CD	varchar(50)		,
	BLDG_ID	INTEGER		,
	SUB_BLDG_ID	INTEGER		,
	PREMS_CD	varchar(50)		,
	THOROUGHFARE_CD	varchar(50)		,
	LOB_NUM	INTEGER		,
	DSTRCT_NAME	varchar(50)		,
	CNTY_NAME	varchar(50)		,
	ZIP_EXTN	varchar(20)		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_STREET_24_PK PRIMARY KEY(STREET_ADDR_RQST_ID) 
)  ;

ALTER TABLE MDM41_STG.STREET_ADDR_RQST_STG ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_STG.STREET_ADDR_RQST_STG ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_STG.STREET_ADDR_RSULT_STG (	STREET_ADDR_RQST_ID	INTEGER		 NOT NULL,
	PRSNA_ID	INTEGER		,
	ADDR_LINE_1_TXT	varchar(1000)		,
	ADDR_LINE_2_TXT	varchar(1000)		,
	ADDR_LINE_3_TXT	varchar(1000)		,
	ADDR_LINE_4_TXT	varchar(1000)		,
	ST_OR_PROV_CD	varchar(50)		,
	CITY_NAME	varchar(100)		,
	POSTL_CD	varchar(50)		,
	LAT_MEAS	DECIMAL(18,4)		,
	LNGTD_MEAS	DECIMAL(18,4)		,
	CTRY_ID	INTEGER		,
	GEO_ACRCY_CD	varchar(50)		,
	ORG_CD	varchar(50)		,
	BLDG_ID	INTEGER		,
	SUB_BLDG_ID	INTEGER		,
	PREMS_CD	varchar(50)		,
	THOROUGHFARE_CD	varchar(50)		,
	ADDR_RSULT_CD	varchar(50)		,
	LOB_NUM	INTEGER		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_STREET_26_PK PRIMARY KEY(STREET_ADDR_RQST_ID) 
)  ;

ALTER TABLE MDM41_STG.STREET_ADDR_RSULT_STG ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_STG.STREET_ADDR_RSULT_STG ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_STG.TEL_NUM_RQST_STG (	TEL_NUM_RQST_ID	INTEGER		 NOT NULL,
	PRSNA_ID	INTEGER		,
	TEL_CTRY_CD_NUM	varchar(50)		,
	TEL_AREA_CD_NUM	varchar(50)		,
	TEL_EXCH_NUM	varchar(50)		,
	TEL_LINE_NUM	varchar(50)		,
	TEL_EXTN_NUM	varchar(50)		,
	TEL_E164_NUM	varchar(50)		,
	TEL_SRC_NUM	varchar(50)		,
	TEL_SUB_TYPE_CD	varchar(50)		,
	LOB_NUM	INTEGER		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_TEL_NUM27_PK PRIMARY KEY(TEL_NUM_RQST_ID) 
)  ;

ALTER TABLE MDM41_STG.TEL_NUM_RQST_STG ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_STG.TEL_NUM_RQST_STG ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_STG.TEL_NUM_RSULT_STG (	TEL_NUM_RQST_ID	INTEGER		 NOT NULL,
	PRSNA_ID	INTEGER		,
	TEL_CTRY_CD_NUM	varchar(50)		,
	TEL_AREA_CD_NUM	varchar(50)		,
	TEL_EXCH_NUM	varchar(50)		,
	TEL_LINE_NUM	varchar(50)		,
	TEL_EXTN_NUM	varchar(50)		,
	TEL_E164_NUM	varchar(50)		,
	TEL_SRC_NUM	varchar(50)		,
	TEL_SUB_TYPE_CD	varchar(50)		,
	ADDR_RSULT_CD	varchar(50)		,
	TEL_NATL_FMT_NUM	char(18)		,
	TEL_TM_ZN_CD	char(18)		,
	TEL_OFFLN_GEOCODE_LOC_CD	char(18)		,
	TEL_INTRNATL_FMT_NUM	char(18)		,
	US_OUT_OF_CTRY_FMT_NUM	char(18)		,
	CH_OUT_OF_CTRY_FMT_NUM	char(18)		,
	LOB_NUM	INTEGER		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		)  ;

ALTER TABLE MDM41_STG.TEL_NUM_RSULT_STG ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_STG.TEL_NUM_RSULT_STG ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 


CREATE TABLE MDM41_STG.VEH_DATA_STG (	VEH_ID	INTEGER		 NOT NULL,
	VEH_YR	varchar(20)		,
	MODL_TRIM	varchar(50)		,
	SHPG_DT	DATE		,
	ORIGNL_SLS_DT	DATE		,
	MFGNG_DT	DATE		,
	EURO_FIN	varchar(20)		,
	BODY_STYL_CD	varchar(20)		,
	DOOR_STYL_CD	varchar(20)		,
	FUEL_TYPE_CD	varchar(20)		,
	NVGTN_CD	varchar(20)		,
	TELEMATICS_CD	varchar(20)		,
	HD_UNIT_TYPE_CD	varchar(20)		,
	HD_UNIT_SER_NUM	varchar(50)		,
	HD_UNIT_MODL_NUM	varchar(20)		,
	LIC_PLATE_NUM	varchar(20)		,
	LIC_PLATE_ST	char(2)		,
	VEH_CTGY_CD	varchar(20)		,
	USED_CAR_SLS_IND	char(1)		,
	FLEET_CAR_IND	char(1)		,
	CPO_IND	char(1)		,
	IMPORT_IND	char(1)		,
	NEW_CAR_IND	char(1)		,
	CNTCT_NUM	varchar(20)		,
	PRTNR_NAME	varchar(20)		,
	VEH_VIN	varchar(20)		,
	VIN_PTN	varchar(20)		,
	SRC_INTAKE_ID	varchar(18)		,
	FACTORY_SHPG_DT	DATE		,
	VEH_SLS_MODL_CD	varchar(20)		,
	VEH_MAKE_CD	varchar(20)		,
	VEH_INTRIOR_COLOR_CD	varchar(20)		,
	VEH_EXTRR_COLOR_CD	varchar(20)		,
	ENGN_SLS_NUM	varchar(20)		,
	VEHCILE_SER_NUM	varchar(20)		,
	VEH_ORIGNL_DLR_CD	varchar(20)		,
	ORIGNL_DLR_CD	varchar(20)		,
	ORIGNL_PRTNR_NAME	varchar(20)		,
	VEH_RCALLD_IND	char(1)		,
	XMISN_SER_NUM	varchar(20)		,
	MFGNG_CTRY_CD	varchar(20)		,
	XMISN_TYPE_CD	varchar(20)		,
	DEVICE_ID	INTEGER		,
	LOB_NUM	INTEGER		,
	OEM_MFGR_ID	INTEGER		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_VEH_DAT29_PK PRIMARY KEY(VEH_ID) 
)  ;

ALTER TABLE MDM41_STG.VEH_DATA_STG ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_STG.VEH_DATA_STG ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_STG.VEH_FEAT_DATA_STG (	FEAT_CD	varchar(20)		 NOT NULL,
	VEH_ID	INTEGER		 NOT NULL,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_VEH_FEA30_PK PRIMARY KEY(FEAT_CD,VEH_ID) 
)  PRIMARY INDEX MST_XIE1VEHICLE_FEATURE_DATA (VEH_ID) 
 ;

ALTER TABLE MDM41_STG.VEH_FEAT_DATA_STG ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_STG.VEH_FEAT_DATA_STG ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_STG.VEH_MFG_DATA_STG (	VEH_ID	INTEGER		 NOT NULL,
	VEH_MFG_DATA_CD	varchar(20)		 NOT NULL,
	VEH_MFG_DATA_MEAS_CD	varchar(20)		,
	VEH_MFG_DATA_VAL	DECIMAL(18,4)		,
	VEH_MFG_DATA_DESC	varchar(250)		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_VEH_MFG31_PK PRIMARY KEY(VEH_ID) 
)  ;

ALTER TABLE MDM41_STG.VEH_MFG_DATA_STG ADD CONSTRAINT MST_XPKVEHICLE_MANUFACTURER_DATA UNIQUE (VEH_ID, VEH_MFG_DATA_CD) ;

ALTER TABLE MDM41_STG.VEH_MFG_DATA_STG ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_STG.VEH_MFG_DATA_STG ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_STG.VEH_PRSNA_STG (	VEH_ID	INTEGER		 NOT NULL,
	PRSNA_ID	INTEGER		 NOT NULL,
	LOB_NUM	INTEGER		 NOT NULL,
	PRSNA_ROLE_CD	varchar(50)		,
	SELG_DLR_CD	varchar(20)		,
	SLS_PRSN_NUM	varchar(20)		,
	SELG_PRTNR_NAME	varchar(20)		,
	FRST_OWNR_IND	char(1)		,
	LAST_PREOWNED_DT	DATE		,
	SRVCG_DLR_CD	varchar(20)		,
	SRVCG_PRTNR_NAME	varchar(50)		,
	LEASG_CO_NAME	varchar(50)		,
	EU_DLVRY_IND	char(1)		,
	VEH_SLS_DT	DATE		,
	VEH_SLS_RPT_DT	DATE		,
	VEH_PRSNA_RLTNSHP_TYPE_CD	varchar(20)		,
	PO	varchar(20)		,
	CURR_MILEG	INTEGER		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_VEH_PRS32_PK PRIMARY KEY(VEH_ID,PRSNA_ID,LOB_NUM) 
)  PRIMARY INDEX MST_XIE1VEHICLE_PRSNA (PRSNA_ID) 
 ;

ALTER TABLE MDM41_STG.VEH_PRSNA_STG ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_STG.VEH_PRSNA_STG ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_STG.VEH_XREF_STG (	VEH_ID	INTEGER		 NOT NULL,
	XREF_KEY	varchar(20)		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		, CONSTRAINT MST_VEH_XRE33_PK PRIMARY KEY(VEH_ID) 
)  PRIMARY INDEX MST_XREF_KEY_PI_9937834 (XREF_KEY) 
 ;

ALTER TABLE MDM41_STG.VEH_XREF_STG ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_STG.VEH_XREF_STG ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 


