REPLACE VIEW MDM41.REF_CUST_V AS
LOCKING ROW FOR ACCESS SELECT
CAST(COALESCE(PRTY.GOLDEN_CUST_ID,PRTY.CUST_ID) AS INTEGER) AS CUST_ID,
PRTY_ADDR.ADDR_ID,
PRTY_ADDR.ADDR_TYPE_CD,
CASE WHEN TRIM(UPPER(PRTY_ADDR.ADDR_TYPE_CD))= 'STREET' THEN PRTY_ADDR.ADDR_TYPE_CD END ADDR_TYPE_STREET, 
CASE WHEN TRIM(UPPER(PRTY_ADDR.ADDR_TYPE_CD))= 'TELPHONE' THEN PRTY_ADDR.ADDR_TYPE_CD END ADDR_TYPE_PHONE, 
CASE WHEN TRIM(UPPER(PRTY_ADDR.ADDR_TYPE_CD))= 'EMAIL' THEN PRTY_ADDR.ADDR_TYPE_CD END ADDR_TYPE_EMAIL, 
PRTY.CUST_TYPE_CD,
ORG.ORG_NAME,
IND.FRST_NAME,
IND.MDL_NAME,
IND.LAST_NAME,
IND.NAME_PRFX_TXT,
IND.NAME_SFX_TXT,
IND.GNDR_TYPE_CD,
PRTY.SYS_TARGET_ID,
PRTY.SYS_AUTH_ID,
PRTY.SYS_SOURCE,
PRTY.SYS_CREATED_BY,
PRTY.SYS_CREATION_DATE,
PRTY.SYS_ENT_STATE,
PRTY.SYS_LAST_MODIFIED_BY,
PRTY.SYS_LAST_MODIFIED_DATE,
PRTY.SYS_NC_TYPE,
PRTY.SYS_ERR_CODE,
PRTY.SYS_ERR_SVRTY
FROM	MDM41_MST.M_CUST PRTY
LEFT OUTER JOIN MDM41_MST.M_INDIV_CUST IND ON PRTY.CUST_TYPE_CD='IND' AND PRTY.CUST_ID=IND.CUST_ID
LEFT OUTER JOIN MDM41_MST.M_ORG_CUST ORG ON PRTY.CUST_TYPE_CD ='ORG' AND PRTY.CUST_ID=ORG.CUST_ID AND PRTY.SYS_ENT_STATE='ACTIVE'
INNER JOIN 
(SELECT CUST_ADDR.CUST_ID, CUST_ADDR.ADDR_ID, CUST_ADDR.LOB_NUM, ADDR.ADDR_TYPE_CD, ADDR.ADDR_SUBTYPE_CD FROM MDM41_MST.M_CUST_ADDR CUST_ADDR INNER JOIN MDM41_MST.M_ADDR ADDR ON ADDR.ADDR_ID=CUST_ADDR.ADDR_ID) PRTY_ADDR
ON PRTY.CUST_ID = PRTY_ADDR.CUST_ID AND PRTY.SYS_ENT_STATE='ACTIVE'
;