REPLACE VIEW MDM41.REF_ELEC_ADDR_V
AS
LOCKING ROW FOR ACCESS SELECT	
ELEC_ADDR.ELEC_ADDR_ID,
ADDR.ADDR_ID, 
ADDR.ADDR_TYPE_CD, 
ADDR.ADDR_SUBTYPE_CD, 
ELEC_ADDR.ELEC_ADDR_SBTYPE_CD, 
ELEC_ADDR.DMN_ROOT_CD, 
ELEC_ADDR.ELEC_ADDR_TXT,
ELEC_ADDR.ELEC_ADDR_DMN_NAME,
ELEC_ADDR.SYS_TARGET_ID,
ELEC_ADDR.SYS_AUTH_ID,
ELEC_ADDR.SYS_SOURCE,
ELEC_ADDR.SYS_CREATED_BY,
ELEC_ADDR.SYS_CREATION_DATE,
ELEC_ADDR.SYS_ENT_STATE,
ELEC_ADDR.SYS_LAST_MODIFIED_BY,
ELEC_ADDR.SYS_LAST_MODIFIED_DATE,
ELEC_ADDR.SYS_NC_TYPE,
ELEC_ADDR.SYS_ERR_CODE,
ELEC_ADDR.SYS_ERR_SVRTY
FROM	MDM41_MST.M_ELEC_ADDR ELEC_ADDR
INNER JOIN MDM41_MST.M_ADDR ADDR
ON ELEC_ADDR.ELEC_ADDR_ID = ADDR.ADDR_ID
WHERE ELEC_ADDR.SYS_ENT_STATE='ACTIVE';