REPLACE VIEW MDM41.REF_TEL_NUM_V 
AS
LOCKING ROW FOR ACCESS SELECT	
TEL_NUM.TEL_NUM_ID, 
ADDR.ADDR_ID, 
ADDR.ADDR_TYPE_CD, 
ADDR.ADDR_SUBTYPE_CD, 
TEL_NUM.TEL_CTRY_CD_NUM, 
TEL_NUM.TEL_AREA_CD_NUM, 
TEL_NUM.TEL_EXCH_NUM,
TEL_NUM.TEL_LINE_NUM,
TEL_NUM.TEL_EXTN_NUM,
TEL_NUM.TEL_E164_NUM,
TEL_NUM.TEL_SRC_NUM,
TEL_NUM.TEL_SUB_TYPE_CD,
TEL_NUM.SMS_CPBL_IND,
TEL_NUM.SYS_TARGET_ID,
TEL_NUM.SYS_AUTH_ID,
TEL_NUM.SYS_SOURCE,
TEL_NUM.SYS_CREATED_BY,
TEL_NUM.SYS_CREATION_DATE,
TEL_NUM.SYS_ENT_STATE,
TEL_NUM.SYS_LAST_MODIFIED_BY,
TEL_NUM.SYS_LAST_MODIFIED_DATE,
TEL_NUM.SYS_NC_TYPE,
TEL_NUM.SYS_ERR_CODE,
TEL_NUM.SYS_ERR_SVRTY
FROM	MDM41_MST.M_TEL_NUM TEL_NUM
INNER JOIN MDM41_MST.M_ADDR ADDR
ON TEL_NUM.TEL_NUM_ID = ADDR.ADDR_ID
WHERE TEL_NUM.SYS_ENT_STATE='ACTIVE';