.RUN FILE ../LOGIN_INFO.SQL
 
 .WIDTH 5000;

DEL MDM41_CRDM.XREF_303_REL_KEY ;

INSERT INTO MDM41_CRDM.XREF_303_REL_KEY
SELECT	LVL_1.M_PRSNA_ID AS PRSNA_ID,'DUPE_'||TRIM(MAX(GREATEST((LVL_1.S_PRSNA_ID (VARCHAR(500))) ,
		(LVL_2.S_PRSNA_ID (VARCHAR(500))) ,(LVL_3.S_PRSNA_ID (VARCHAR(500))) ,
		(LVL_4.S_PRSNA_ID (VARCHAR(500))) ))) RELATION_KEY 
FROM	MDM41_CRDM.XREF_304_1 AS LVL_1,MDM41_CRDM.XREF_304_1 AS LVL_2,
		MDM41_CRDM.XREF_304_1 AS LVL_3,MDM41_CRDM.XREF_304_1 AS LVL_4 
WHERE	LVL_2.M_PRSNA_ID = LVL_1.S_PRSNA_ID 
	AND LVL_3.M_PRSNA_ID = LVL_2.S_PRSNA_ID 
	AND LVL_4.M_PRSNA_ID = LVL_3.S_PRSNA_ID 
GROUP BY LVL_1.M_PRSNA_ID ;

INSERT INTO 
MDM41_CRDM.XREF_303_1 (CUST_ID, PRSNA_ID, Score, Survivor_Ind, RUN_ID, RUN_TIMESTAMP) 
SELECT DISTINCT CUST_ID,RELKEY.PRSNA_ID,Score,Survivor_Ind,RUN_ID,RUN_TIMESTAMP FROM 
(SELECT X.CUST_ID,REL.PRSNA_ID,Score,Survivor_Ind,RUN_ID,RUN_TIMESTAMP,REL_KEY
FROM MDM41_CRDM.XREF_303_1 X INNER JOIN 
MDM41_CRDM.XREF_303_REL_KEY REL
ON X.PRSNA_ID=REL.PRSNA_ID) XREF
INNER JOIN MDM41_CRDM.XREF_303_REL_KEY  RELKEY
ON XREF.REL_KEY=RELKEY.REL_KEY;

DELETE FROM MDM41_CRDM.NROW_303
WHERE PRSNA_ID IN (SELECT PRSNA_ID FROM MDM41_CRDM.XREF_303_1) ;

.QUIT
