CREATE TABLE MDM41_MST.M_GROUP (	GROUP_ID	INTEGER		 NOT NULL,
	GROUP_NM	varchar(100)		,
	PARENT_GROUP_ID	INTEGER		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		,
	SYS_WORKFLOW_ID	varchar(100)		, CONSTRAINT M_GROUP_PK PRIMARY KEY(GROUP_ID) 
)  ;

REPLACE VIEW M_GROUP AS SELECT * FROM MDM41_MST.M_GROUP ;

ALTER TABLE MDM41_MST.M_GROUP ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_MST.M_GROUP ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_MST.M_GROUP_JOB_RUN (	JOB_GROUP_RUN_ID	varchar(50)		 NOT NULL,
	SRC_INTAKE_CD	varchar(100)		,
	DATA_SOURCE	varchar(100)		,
	DATA_SOURCE_TYPE	varchar(100)		,
	STATUS_ID	INTEGER		,
	START_DTTM	TIMESTAMP(0)		,
	END_DTTM	TIMESTAMP(0)		,
	SRC_JOB_RUN_ID	varchar(50)		,
	EXECUTE_TEXT	varchar(1000)		,
	LOG_FILE_NM	varchar(1000)		,
	JOB_ERROR_MESSAGE_TEXT	varchar(1000)		,
	ERROR_TABLE_NM	varchar(100)		,
	ERROR_RESOLVED_FLAG	char(1)		,
	SOURCE_COUNT	INTEGER		,
	TARGET_COUNT	INTEGER		,
	ERROR_COUNT	INTEGER		,
	NOTIFICATION_STATUS	varchar(40)		 DEFAULT 'NOT_PROCESSED' ,
	ROW_ERROR_FILE	varchar(100)		,
	ERROR_PERCENT	INTEGER		,
	DUP_COUNT	INTEGER		,
	WARNING_COUNT	INTEGER		,
	GROUP_ID	INTEGER		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		,
	SYS_WORKFLOW_ID	varchar(100)		, CONSTRAINT M_GROUP_JOB_RUN_PK PRIMARY KEY(JOB_GROUP_RUN_ID) 
)  PRIMARY INDEX MST_JOB_RUN_FK1 (STATUS_ID) 
 ;

REPLACE VIEW M_GROUP_JOB_RUN AS SELECT * FROM MDM41_MST.M_GROUP_JOB_RUN ;

CREATE INDEX MST_JOB_RUN_FK2 (SRC_INTAKE_CD, END_DTTM) ON MDM41_MST.M_GROUP_JOB_RUN ;

ALTER TABLE MDM41_MST.M_GROUP_JOB_RUN ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_MST.M_GROUP_JOB_RUN ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_MST.M_JOB_GROUP (	GROUP_ID	INTEGER		 NOT NULL,
	JOB_ID	INTEGER		 NOT NULL,
	SEQUENCE_ID	INTEGER		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		,
	SYS_WORKFLOW_ID	varchar(100)		, CONSTRAINT M_JOB_GROUP_PK PRIMARY KEY(GROUP_ID,JOB_ID) 
)  PRIMARY INDEX MST_XIE1MST_JOB_GROUP (JOB_ID) 
 ;

REPLACE VIEW M_JOB_GROUP AS SELECT * FROM MDM41_MST.M_JOB_GROUP ;

ALTER TABLE MDM41_MST.M_JOB_GROUP ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_MST.M_JOB_GROUP ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_MST.M_JOB_MASTER (	JOB_ID	INTEGER		 NOT NULL,
	JOB_NM	varchar(100)		,
	FILE_IDENTIFIER	INTEGER		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		,
	SYS_WORKFLOW_ID	varchar(100)		, CONSTRAINT M_JOB_MASTER_PK PRIMARY KEY(JOB_ID) 
)  ;

REPLACE VIEW M_JOB_MASTER AS SELECT * FROM MDM41_MST.M_JOB_MASTER ;

ALTER TABLE MDM41_MST.M_JOB_MASTER ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_MST.M_JOB_MASTER ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_MST.M_JOB_RUN_DETAILS (	JOB_RUN_ID	varchar(50)		 NOT NULL,
	EXECUTE_TEXT	varchar(1000)		,
	LOG_FILE_NAME	varchar(1000)		,
	JOB_ERROR_MESSAGE_TEXT	varchar(1000)		,
	ERROR_TABLE_NAME	varchar(100)		,
	ERROR_RESOLVED_FLAG	char(1)		,
	SOURCE_COUNT	INTEGER		,
	TARGET_COUNT	INTEGER		,
	ERROR_COUNT	INTEGER		,
	JOB_ID	INTEGER		 NOT NULL,
	JOB_GROUP_RUN_ID	varchar(50)		,
	STATUS_ID	INTEGER		,
	START_DTTM	TIMESTAMP(0)		,
	END_DTTM	TIMESTAMP(0)		,
	ERROR_PERCENT	INTEGER		,
	WARNING_COUNT	INTEGER		,
	ROW_ERROR_FILE	varchar(100)		,
	DUP_COUNT	INTEGER		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		,
	SYS_WORKFLOW_ID	varchar(100)		, CONSTRAINT M_JOB_RUN_D1_PK PRIMARY KEY(JOB_RUN_ID,JOB_ID) 
)  ;

REPLACE VIEW M_JOB_RUN_DETAILS AS SELECT * FROM MDM41_MST.M_JOB_RUN_DETAILS ;

ALTER TABLE MDM41_MST.M_JOB_RUN_DETAILS ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_MST.M_JOB_RUN_DETAILS ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_MST.M_SOURCE_FILE (	FILE_IDENTIFIER	INTEGER		 NOT NULL,
	SOURCE_INTAKE_ID	char(18)		 NOT NULL,
	FILE_NAME	varchar(20)		,
	FILE_DESCRIPTION	char(18)		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		,
	SYS_WORKFLOW_ID	varchar(100)		, CONSTRAINT M_SOURCE_FILE_PK PRIMARY KEY(FILE_IDENTIFIER) 
)  ;

REPLACE VIEW M_SOURCE_FILE AS SELECT * FROM MDM41_MST.M_SOURCE_FILE ;

ALTER TABLE MDM41_MST.M_SOURCE_FILE ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_MST.M_SOURCE_FILE ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_MST.M_SOURCE_INTAKE (	SOURCE_INTAKE_ID	char(18)		 NOT NULL,
	SOURCE_TYPE_CD	varchar(50)		 NOT NULL,
	SOURCE_TYPE_DESC	varchar(250)		,
	SOURCE_TYPE_NAME	varchar(100)		,
	SOURCE_PROVIDER_CD	varchar(50)		,
	SOURCE_FOLDER_TXT	varchar(1000)		,
	SFTP_FLAG	char(3)		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		,
	SYS_WORKFLOW_ID	varchar(100)		, CONSTRAINT M_SOURCE_INTAKE_PK PRIMARY KEY(SOURCE_INTAKE_ID) 
)  ;

REPLACE VIEW M_SOURCE_INTAKE AS SELECT * FROM MDM41_MST.M_SOURCE_INTAKE ;

ALTER TABLE MDM41_MST.M_SOURCE_INTAKE ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_MST.M_SOURCE_INTAKE ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

CREATE TABLE MDM41_MST.M_STATUS (	STATUS_ID	INTEGER		 NOT NULL,
	STATUS_NM	varchar(100)		,
	SYS_TARGET_ID	INTEGER		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_CREATED_BY	varchar(70)		,
	SYS_CREATION_DATE	TIMESTAMP(0)		,
	SYS_ENT_STATE	varchar(25)		,
	SYS_LAST_MODIFIED_BY	varchar(70)		,
	SYS_LAST_MODIFIED_DATE	TIMESTAMP(0)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_ERR_SVRTY	varchar(30)		,
	SYS_WORKFLOW_ID	varchar(100)		, CONSTRAINT M_STATUS_PK PRIMARY KEY(STATUS_ID) 
)  ;

REPLACE VIEW M_STATUS AS SELECT * FROM MDM41_MST.M_STATUS ;

ALTER TABLE MDM41_MST.M_STATUS ADD SYS_ENT_STATE CHECK ( SYS_ENT_STATE  IN ('ACTIVE','INACTIVE','NEW','DELETED') ); 

ALTER TABLE MDM41_MST.M_STATUS ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING') ); 

-- ERROR: This DDL will fail.

-- Removed drop statement for Primary Index: TEL_NUM_RSULT_CNTRT_44396 on Table: TEL_NUM_RSULT

CREATE TABLE MDM41_MST.E_GROUP (	GROUP_ID	varchar(25)		,
	GROUP_NM	varchar(100)		,
	PARENT_GROUP_ID	varchar(25)		,
	SYS_TARGET_ID	varchar(10)		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_ERROR_ID	INTEGER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 2 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE)		 NOT NULL,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_UPDATED	varchar(15)		,
	SYS_ERROR_TIME	varchar(20)		,
	SYS_ERR_SVRTY	varchar(30)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_DOCUMENT	varchar(100)		 DEFAULT 'GROUP' ,
	SYS_LOAD_ID	varchar(32)		,
	SYS_WORKFLOW_ID	varchar(100)		,
	SYS_VER_ID	INTEGER		, CONSTRAINT E_GROUP_PK PRIMARY KEY(SYS_ERROR_ID) 
)  ;

REPLACE VIEW E_GROUP AS SELECT * FROM MDM41_MST.E_GROUP ;

ALTER TABLE MDM41_MST.E_GROUP ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING','REJECTED') ); 

CREATE TABLE MDM41_MST.E_GROUP_JOB_RUN (	JOB_GROUP_RUN_ID	varchar(50)		,
	SRC_INTAKE_CD	varchar(100)		,
	DATA_SOURCE	varchar(100)		,
	DATA_SOURCE_TYPE	varchar(100)		,
	STATUS_ID	varchar(25)		,
	START_DTTM	varchar(50)		,
	END_DTTM	varchar(50)		,
	SRC_JOB_RUN_ID	varchar(50)		,
	EXECUTE_TEXT	varchar(1000)		,
	LOG_FILE_NM	varchar(1000)		,
	JOB_ERROR_MESSAGE_TEXT	varchar(1000)		,
	ERROR_TABLE_NM	varchar(100)		,
	ERROR_RESOLVED_FLAG	char(1)		,
	SOURCE_COUNT	varchar(25)		,
	TARGET_COUNT	varchar(25)		,
	ERROR_COUNT	varchar(25)		,
	NOTIFICATION_STATUS	varchar(40)		,
	ROW_ERROR_FILE	varchar(100)		,
	ERROR_PERCENT	varchar(25)		,
	DUP_COUNT	varchar(25)		,
	WARNING_COUNT	varchar(25)		,
	GROUP_ID	varchar(25)		,
	SYS_TARGET_ID	varchar(10)		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_ERROR_ID	INTEGER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 2 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE)		 NOT NULL,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_UPDATED	varchar(15)		,
	SYS_ERROR_TIME	varchar(20)		,
	SYS_ERR_SVRTY	varchar(30)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_DOCUMENT	varchar(100)		 DEFAULT 'GROUP_JOB_RUN' ,
	SYS_LOAD_ID	varchar(32)		,
	SYS_WORKFLOW_ID	varchar(100)		,
	SYS_VER_ID	INTEGER		, CONSTRAINT E_GROUP_JOB_RUN_PK PRIMARY KEY(SYS_ERROR_ID) 
)  ;

REPLACE VIEW E_GROUP_JOB_RUN AS SELECT * FROM MDM41_MST.E_GROUP_JOB_RUN ;

ALTER TABLE MDM41_MST.E_GROUP_JOB_RUN ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING','REJECTED') ); 

CREATE TABLE MDM41_MST.E_JOB_GROUP (	GROUP_ID	varchar(25)		,
	JOB_ID	varchar(25)		,
	SEQUENCE_ID	varchar(25)		,
	SYS_TARGET_ID	varchar(10)		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_ERROR_ID	INTEGER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 2 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE)		 NOT NULL,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_UPDATED	varchar(15)		,
	SYS_ERROR_TIME	varchar(20)		,
	SYS_ERR_SVRTY	varchar(30)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_DOCUMENT	varchar(100)		 DEFAULT 'JOB_GROUP' ,
	SYS_LOAD_ID	varchar(32)		,
	SYS_WORKFLOW_ID	varchar(100)		,
	SYS_VER_ID	INTEGER		, CONSTRAINT E_JOB_GROUP_PK PRIMARY KEY(SYS_ERROR_ID) 
)  ;

REPLACE VIEW E_JOB_GROUP AS SELECT * FROM MDM41_MST.E_JOB_GROUP ;

ALTER TABLE MDM41_MST.E_JOB_GROUP ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING','REJECTED') ); 

CREATE TABLE MDM41_MST.E_JOB_MASTER (	JOB_ID	varchar(25)		,
	JOB_NM	varchar(100)		,
	FILE_IDENTIFIER	varchar(25)		,
	SYS_TARGET_ID	varchar(10)		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_ERROR_ID	INTEGER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 2 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE)		 NOT NULL,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_UPDATED	varchar(15)		,
	SYS_ERROR_TIME	varchar(20)		,
	SYS_ERR_SVRTY	varchar(30)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_DOCUMENT	varchar(100)		 DEFAULT 'JOB_MASTER' ,
	SYS_LOAD_ID	varchar(32)		,
	SYS_WORKFLOW_ID	varchar(100)		,
	SYS_VER_ID	INTEGER		, CONSTRAINT E_JOB_MASTER_PK PRIMARY KEY(SYS_ERROR_ID) 
)  ;

REPLACE VIEW E_JOB_MASTER AS SELECT * FROM MDM41_MST.E_JOB_MASTER ;

ALTER TABLE MDM41_MST.E_JOB_MASTER ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING','REJECTED') ); 

CREATE TABLE MDM41_MST.E_JOB_RUN_DETAILS (	JOB_RUN_ID	varchar(50)		,
	EXECUTE_TEXT	varchar(1000)		,
	LOG_FILE_NAME	varchar(1000)		,
	JOB_ERROR_MESSAGE_TEXT	varchar(1000)		,
	ERROR_TABLE_NAME	varchar(100)		,
	ERROR_RESOLVED_FLAG	char(1)		,
	SOURCE_COUNT	varchar(25)		,
	TARGET_COUNT	varchar(25)		,
	ERROR_COUNT	varchar(25)		,
	JOB_ID	varchar(25)		,
	JOB_GROUP_RUN_ID	varchar(50)		,
	STATUS_ID	varchar(25)		,
	START_DTTM	varchar(50)		,
	END_DTTM	varchar(50)		,
	ERROR_PERCENT	varchar(25)		,
	WARNING_COUNT	varchar(25)		,
	ROW_ERROR_FILE	varchar(100)		,
	DUP_COUNT	varchar(25)		,
	SYS_TARGET_ID	varchar(10)		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_ERROR_ID	INTEGER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 2 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE)		 NOT NULL,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_UPDATED	varchar(15)		,
	SYS_ERROR_TIME	varchar(20)		,
	SYS_ERR_SVRTY	varchar(30)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_DOCUMENT	varchar(100)		 DEFAULT 'JOB_RUN_DETAILS' ,
	SYS_LOAD_ID	varchar(32)		,
	SYS_WORKFLOW_ID	varchar(100)		,
	SYS_VER_ID	INTEGER		, CONSTRAINT E_JOB_RUN_D2_PK PRIMARY KEY(SYS_ERROR_ID) 
)  ;

REPLACE VIEW E_JOB_RUN_DETAILS AS SELECT * FROM MDM41_MST.E_JOB_RUN_DETAILS ;

ALTER TABLE MDM41_MST.E_JOB_RUN_DETAILS ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING','REJECTED') ); 

CREATE TABLE MDM41_MST.E_SOURCE_FILE (	FILE_IDENTIFIER	varchar(25)		,
	SOURCE_INTAKE_ID	char(18)		,
	FILE_NAME	varchar(20)		,
	FILE_DESCRIPTION	char(18)		,
	SYS_TARGET_ID	varchar(10)		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_ERROR_ID	INTEGER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 2 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE)		 NOT NULL,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_UPDATED	varchar(15)		,
	SYS_ERROR_TIME	varchar(20)		,
	SYS_ERR_SVRTY	varchar(30)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_DOCUMENT	varchar(100)		 DEFAULT 'SOURCE_FILE' ,
	SYS_LOAD_ID	varchar(32)		,
	SYS_WORKFLOW_ID	varchar(100)		,
	SYS_VER_ID	INTEGER		, CONSTRAINT E_SOURCE_FILE_PK PRIMARY KEY(SYS_ERROR_ID) 
)  ;

REPLACE VIEW E_SOURCE_FILE AS SELECT * FROM MDM41_MST.E_SOURCE_FILE ;

ALTER TABLE MDM41_MST.E_SOURCE_FILE ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING','REJECTED') ); 

CREATE TABLE MDM41_MST.E_SOURCE_INTAKE (	SOURCE_INTAKE_ID	char(18)		,
	SOURCE_TYPE_CD	varchar(50)		,
	SOURCE_TYPE_DESC	varchar(250)		,
	SOURCE_TYPE_NAME	varchar(100)		,
	SOURCE_PROVIDER_CD	varchar(50)		,
	SOURCE_FOLDER_TXT	varchar(1000)		,
	SFTP_FLAG	char(3)		,
	SYS_TARGET_ID	varchar(10)		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_ERROR_ID	INTEGER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 2 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE)		 NOT NULL,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_UPDATED	varchar(15)		,
	SYS_ERROR_TIME	varchar(20)		,
	SYS_ERR_SVRTY	varchar(30)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_DOCUMENT	varchar(100)		 DEFAULT 'SOURCE_INTAKE' ,
	SYS_LOAD_ID	varchar(32)		,
	SYS_WORKFLOW_ID	varchar(100)		,
	SYS_VER_ID	INTEGER		, CONSTRAINT E_SOURCE_INTAKE_PK PRIMARY KEY(SYS_ERROR_ID) 
)  ;

REPLACE VIEW E_SOURCE_INTAKE AS SELECT * FROM MDM41_MST.E_SOURCE_INTAKE ;

ALTER TABLE MDM41_MST.E_SOURCE_INTAKE ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING','REJECTED') ); 

CREATE TABLE MDM41_MST.E_STATUS (	STATUS_ID	varchar(25)		,
	STATUS_NM	varchar(100)		,
	SYS_TARGET_ID	varchar(10)		,
	SYS_AUTH_ID	varchar(1000)		,
	SYS_SOURCE	varchar(256)		 DEFAULT 'BackEnd' ,
	SYS_ERROR_ID	INTEGER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 2 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE)		 NOT NULL,
	SYS_ERR_CODE	varchar(10000)		,
	SYS_UPDATED	varchar(15)		,
	SYS_ERROR_TIME	varchar(20)		,
	SYS_ERR_SVRTY	varchar(30)		,
	SYS_NC_TYPE	varchar(25)		,
	SYS_DOCUMENT	varchar(100)		 DEFAULT 'STATUS' ,
	SYS_LOAD_ID	varchar(32)		,
	SYS_WORKFLOW_ID	varchar(100)		,
	SYS_VER_ID	INTEGER		, CONSTRAINT E_STATUS_PK PRIMARY KEY(SYS_ERROR_ID) 
)  ;

REPLACE VIEW E_STATUS AS SELECT * FROM MDM41_MST.E_STATUS ;

ALTER TABLE MDM41_MST.E_STATUS ADD SYS_ERR_SVRTY CHECK ( SYS_ERR_SVRTY  IN ('SEVERE_ERROR','ERROR','WARNING','REJECTED') ); 

